# Dependencies
markdown:         kramdown
highlighter:      Rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            "Learning OSS"
tagline:          'Personal Blog'
description:      '"Live as if you were to die tomorrow. Learn as if you were to live forever." <span style="font-size:18px">- Mahatma Gandhi <span/>'
disclosure:       "All content expressed (my ideas and opinions) in this blog is written by me. I don't represent any company and the content doesn't have any warranty."
url:              http://learningoss.com
baseurl:          /

author:
  name:           'Edison Garcia'
  url:            https://twitter.com/egachi

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/egachi


# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md


sass:
  sass_dir: _sass
  style: :compressed