# Dependencies
# Configuration https://github.com/poole/hyde
markdown:         kramdown
highlighter:      rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            "Emprendiendo"
tagline:          'Blog de un emprendedor'
description:      '"Comienza donde estás. Usa lo que tienes. Haz lo que puedas." <span style="font-size:18px">- Arthur Ashe<span/>'
disclosure:       ""
url:              https://emprendiendo.blog
baseurl:          /

author:
  name:           'Edison Garcia'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           

# Google Analytics
google_analytics: G-1TBFBV5B1S

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed